PREFIX ?= /usr/local
DESTDIR ?=

.PHONY: install uninstall test smoke clean audit backend deb

install:
	install -Dm755 bin/mirdispo "$(DESTDIR)$(PREFIX)/bin/mirdispo"
	install -d "$(DESTDIR)$(PREFIX)/lib/mirdispo/mirdispo"
	cp -R src/mirdispo/. "$(DESTDIR)$(PREFIX)/lib/mirdispo/mirdispo/"
	find "$(DESTDIR)$(PREFIX)/lib/mirdispo" -type d -name __pycache__ -prune -exec rm -r {} +
	install -Dm644 io.github.hencyber.Mirdispo.desktop \
		"$(DESTDIR)$(PREFIX)/share/applications/io.github.hencyber.Mirdispo.desktop"
	install -Dm644 io.github.hencyber.Mirdispo.metainfo.xml \
		"$(DESTDIR)$(PREFIX)/share/metainfo/io.github.hencyber.Mirdispo.metainfo.xml"
	install -Dm755 vendor/amd64/mirdispo-daemon \
		"$(DESTDIR)$(PREFIX)/libexec/mirdispo-daemon"
	install -Dm755 vendor/amd64/gnome-network-displays-stream \
		"$(DESTDIR)$(PREFIX)/libexec/gnome-network-displays-stream"
	install -d "$(DESTDIR)$(PREFIX)/share/icons"
	cp -R assets/icons/hicolor "$(DESTDIR)$(PREFIX)/share/icons/"
	install -Dm644 vendor/source/gnome-network-displays-0.99.0.tar.xz \
		"$(DESTDIR)$(PREFIX)/share/doc/mirdispo/gnome-network-displays-0.99.0.tar.xz"

uninstall:
	rm -f "$(DESTDIR)$(PREFIX)/bin/mirdispo"
	rm -rf "$(DESTDIR)$(PREFIX)/lib/mirdispo"
	rm -f "$(DESTDIR)$(PREFIX)/share/applications/io.github.hencyber.Mirdispo.desktop"
	rm -f "$(DESTDIR)$(PREFIX)/share/metainfo/io.github.hencyber.Mirdispo.metainfo.xml"
	rm -f "$(DESTDIR)$(PREFIX)/libexec/mirdispo-daemon"
	rm -f "$(DESTDIR)$(PREFIX)/libexec/gnome-network-displays-stream"

test:
	python3 -m unittest discover -s tests -v
	@if [ -f work/gnd-build/build.ninja ]; then \
		tests/run-c-tests.sh; \
	else \
		echo "skipping backend C tests: no build in work/gnd-build"; \
	fi

smoke:
	QT_QPA_PLATFORM=offscreen QT_QUICK_CONTROLS_STYLE=Basic \
		./bin/mirdispo --demo --exit-after 1

GND_TARBALL := vendor/source/gnome-network-displays-0.99.0.tar.xz

# Rebuilds the streaming engine from the pristine upstream release plus our
# patches, so the binaries in vendor/amd64/ always match published source.
backend:
	rm -rf work/gnd-source work/gnd-build
	mkdir -p work/gnd-source vendor/amd64
	tar -xf $(GND_TARBALL) -C work/gnd-source --strip-components=1
	for p in packaging/patches/*.patch; do \
		patch -d work/gnd-source -p1 --no-backup-if-mismatch -s < "$$p" || exit 1; \
	done
	meson setup work/gnd-build work/gnd-source --prefix=/usr --buildtype=release -Dbuild_app=false -Dbus_prefix=io.github.hencyber.Mirdispo
	ninja -C work/gnd-build
	install -m755 work/gnd-build/src/gnome-network-displays-stream vendor/amd64/gnome-network-displays-stream
	install -m755 work/gnd-build/src/gnome-network-displays-daemon vendor/amd64/mirdispo-daemon
	strip vendor/amd64/gnome-network-displays-stream vendor/amd64/mirdispo-daemon

deb:
	packaging/build-deb.sh

# Removes everything that is regenerated by a build. Build directories and
# Python caches record the absolute path they were produced in, which means
# the account name of whoever built them, so this is also what to run before
# handing the tree to anyone else.
clean:
	rm -rf work/gnd-build
	find . -name __pycache__ -prune -exec rm -rf {} +
	find . -name '*.pyc' -delete
	# The C tests are linked into work/ and carry the path they were built in.
	find work -maxdepth 1 -type f -executable -delete

# Reports anything in the tree that identifies the machine or account it was
# built on. Run it before sharing the tree or publishing an archive.
audit:
	packaging/privacy-audit.sh
